// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kinbtmwzyjdhxewnnoov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbmJ0bXd6eWpkaHhld25ub292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjI3NjYsImV4cCI6MjA3MDczODc2Nn0.P_9jFcd5ZNAiwdRQNcLKRvRJhwV4fynzY46dJs3277Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});